SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS RESERVER;
DROP TABLE IF EXISTS PONEY_RESERVE;
DROP TABLE IF EXISTS SEANCE;
DROP TABLE IF EXISTS COURS;
DROP TABLE IF EXISTS OBTENIR_LVL;
DROP TABLE IF EXISTS NIVEAU;
DROP TABLE IF EXISTS PONEY;
DROP TABLE IF EXISTS RACE;
DROP TABLE IF EXISTS COTISATION_CLIENT;
DROP TABLE IF EXISTS CLIENT;
DROP TABLE IF EXISTS ADMIN;
DROP TABLE IF EXISTS ENCADRANT;
DROP TABLE IF EXISTS PERSONNE;

SET FOREIGN_KEY_CHECKS=1;